### PR TITLE
Switch Anbox Cloud appliance to Juju 2.9

### PR DESCRIPTION
**Pull request by morphis**
We do not support 2.8 anymore and the user must run 2.9

### CODE REVIEW

**Comment by luis4a0** [comment]
Hey @morphis, thanks! I'm OK with approving this, but please let us check first why CI is failing on MacOS 12.

**Comment by ricab** [comment]
It looks like the cloud-init timed out. I wonder if the runner is starved of resources... let's try again.

**Comment by ricab** [comment]
OK, this is passing in most setups and timing out on a specific job. We know that unfortunately our CI infrastructure is lacking in resources ATM, and that is by far the most likely explanation, so we just have to merge manually.

**Review by ricab — APPROVED** [review]
LGTM, thank you!

**Comment by ricab** [comment]
Well, I'll just try to bors one more time.

bors r+

**Comment by morphis** [comment]
thanks all!

**Pull request merged**
