### PR TITLE
[jellyfin] blueprint

### PR DESCRIPTION
**Pull request by ethicnology**
https://github.com/canonical/multipass/issues/2550

### CODE REVIEW

**Comment by townsend2010** [comment]
Hey @nathan-j-hart, any opinions about adding this as a Blueprint?

**Comment by nathan-j-hart** [comment]
I think it's a great idea! Timing is interesting with us making some improvements to blueprints in the near future. @ethicnology I'd love to get this into Multipass soon - would you be willing to stay in touch as we rework the process?

**Comment by ethicnology** [comment]
@nathan-j-hart Of course, I use Jellyfin with multipass every day, it would be an honor to contribute to these two projects.

I will just have a little latency because of holidays

**Comment by townsend2010** [comment]
Ok, I'm going to merge this in its current state and it will be available as an available shortly.

@ethicnology, thanks for the contribution and willingness to maintain this!  We will reach out to you as needed and also to let you when we have enhancements in place that may be of interest to you.

**Review by townsend2010 — APPROVED** [review]
Ok, LGTM!  Thanks!

**Pull request merged**
