### PR TITLE
Add rockcraft to the docker blueprint

### PR DESCRIPTION
**Pull request by sed-i**
- Install LXD correctly (iptables and all)
- Install rockcraft

Tested manually by copying the cloud init part into its own yaml and
```
multipass launch --cloud-init v1/docker-cloud-config.yaml --name docker-new --mem 4G --cpus 3 --disk 20G
```

### CODE REVIEW

**Review by townsend2010 — CHANGES_REQUESTED** [review]
Hi @sed-i!

I think the Docker Blueprint should really be only for Docker itself.

If you want a Rockcraft specific Blueprint, I'm open to you adding that, but as a separate Blueprint.  You could even pare it down by not including Portainer and anything else specific to the Docker Blueprint itself.

**Comment by townsend2010** [comment]
Hey @sed-i,

I say if `rockcraft` is pretty relevant to what's already contained in the `charm-dev` Blueprint, I'm fine with that.  One thing is that the `charm-dev` Blueprint already does quite a bit of bootstrapping at `launch` and this will just make it even more heavy.  That said, `charm-dev` is intended for developers, so if they are ok with this, then I am too.

**Comment by ricab** [comment]
@sed-i, are you OK with closing this now?

**Comment by ricab** [comment]
Alright, going ahead and closing this. Please reopen if necessary.

**Comment by sed-i** [comment]
Sorry @ricab, just saw this now.
Rockcraft is [now part of charm-dev](https://github.com/canonical/multipass-blueprints/pull/45), so solves some set of problems :)

I think more than anything else, the value of this PR was in the iptables commands that let docker coexist with rockcraft.
In any case, we can keep this closed.

**Pull request closed without merging**
