### PR TITLE
[ci] add integration tests for blueprints

### PR DESCRIPTION
**Pull request by Saviq**
1. Adds a top-level `health-check` script to be executed on the main instance as a health check.
2. On pull requests, test the modified blueprints across a set of drivers
3. Add a manual trigger for testing a particular blueprint

### CODE REVIEW

**Review by townsend2010 — COMMENTED** [review]
The `charm-dev` Blueprint is failing quite regularly due to the Testflinger VM having to run the OOM killer and things go bad- https://github.com/canonical/multipass-blueprints/runs/6132071208?check_suite_focus=true#step:7:3643

**Comment by Saviq** [comment]
> As discussed, I've added another 512MB, which should account for the extra qemu overhead.

With some more tests, I conclude it's not feasible to run the `charm-dev` workflow nested, so I've excluded that from the run.

This is ready to go, #17 exercises it, and multipass/canonical#2542 was filed with a bug it exposed.

**Review by townsend2010 — CHANGES_REQUESTED** [review]
This is good, but I think the macOS `x86_64` runs should be using the `qemu` driver since we are going to be deprecating `hyperkit` soon.

**Comment by Saviq** [comment]
Let's try it again. It did time out, so likely a test infrastructure problem. Something to consider before merging this?

**Comment by Saviq** [comment]
So yeah…

```
Timed out waiting for instance launch.
```

Let me know what you'd like to do?

**Review by townsend2010 — APPROVED** [review]
Ok, I think this is good.  Thanks!

**Pull request merged**
