### PR TITLE
bors: add initial config

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Comment by Saviq** [comment]
bors ping

**Comment by Saviq** [comment]
bors ping

**Comment by Saviq** [comment]
bors try

**Comment by Saviq** [comment]
Oops.

bors try

**Review by townsend2010 — APPROVED** [review]
LGTM!

bors merge

**Comment by townsend2010** [comment]
It seems the Linux minikube integration test is quite reliably OOM'ing the `multipassd` process and failing.  Not sure what to do about that.

**Comment by townsend2010** [comment]
Something's not happy....https://github.com/canonical/multipass-blueprints/runs/7749913926?check_suite_focus=true

**Comment by Saviq** [comment]
bors retry

**Comment by Saviq** [comment]
Gave it moar time to download the images.

bors retry

**Pull request merged**
