### PR TITLE
charm-dev updates

### PR DESCRIPTION
**Pull request by sed-i**
- Enable cluster access by dumping microk8s config.
- Install gnome-keyring, which is [needed](https://github.com/canonical/charmcraft/issues/719#issuecomment-1087643162) by charmcraft

### CODE REVIEW

**Review by Saviq — APPROVED** [review]
Works fine, would it make sense to actually preinstall (one of) those tools?

**Comment by sed-i** [comment]
> Works fine, would it make sense to actually preinstall (one of) those tools?

For me personally yes, but to do it properly cross platform would entail `go get` for k9s or `cargo install` for kdash, which would noticeably increase deployment times. I would definitely add e.g. k9s if it becomes available via apt.

**Comment by Saviq** [comment]
@sed-i why the keyring?

And ACK on k9s/dash. Something to solve with a custom image that has these built in.

**Comment by sed-i** [comment]
> @sed-i why the keyring?

Recent versions of charmcraft won't work without it:
https://github.com/canonical/charmcraft/issues/719#issuecomment-1087643162

**Comment by Saviq** [comment]
> Recent versions of charmcraft won't work without it: [canonical/charmcraft#719 (comment)](https://github.com/canonical/charmcraft/issues/719#issuecomment-1087643162)

Oh, does that mean you now need to run that D-Bus stuff manually to use charmcraft? MEH!

**Comment by sed-i** [comment]
> Oh, does that mean you now need to run that D-Bus stuff manually to use charmcraft? MEH!

Unfortunately, yes. But it works.

**Comment by sed-i** [comment]
@Saviq is this ok to merge?

**Comment by Saviq** [comment]
@sed-i yes, I just got my write rights back on this repo, so here goes ;)

**Pull request merged**
