### PR TITLE
Simplify Anbox Cloud appliance blueprint

### PR DESCRIPTION
**Pull request by morphis**
See commit messages for details.

### CODE REVIEW

**Review by Sploder12 — COMMENTED** [review]
Seems cloud-init is timing out in CI. I don't think these changes would increase the launch time, correct? Rather, this seems like an [existing](https://github.com/canonical/multipass-blueprints/pull/26) issue. I wonder if we should increase the timeout?

**Comment by morphis** [comment]
@Sploder12 No, the changes should not necessarily increase time spent during the installation. We install less snaps and the new appliance snap is smaller than the old one (100MB vs 160MB).

The timeout you mention is within a workflow?

**Comment by Sploder12** [comment]
@morphis Yes, the timeout can be found in `v1/anbox-cloud-appliance.yaml`

**Comment by Sploder12** [comment]
Hey @morphis, what's the status on this?

**Comment by morphis** [comment]
@Sploder12 sorry, for my late reply. Thanks for merging! Do you still want me to fix anything?

**Comment by Sploder12** [comment]
No worries, it only had issues with CI so it's good now. Local testing revealed no issues!

**Pull request merged**
